import Head from "next/head";
import styles from "../styles/Home.module.css";
import BlogFeed from "../components/BlogFeed";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav></nav>
      <main>
        <BlogFeed />
      </main>
    </div>
  );
}
