import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Navbar from "../../components/Navbar";

export default function Post({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main>
        {data && (
          <div
            dangerouslySetInnerHTML={{ __html: data?.content?.rendered }}
          ></div>
        )}
      </main>
    </div>
  );
}

export async function getStaticPaths() {
  const res = await fetch("http://localhost/wp-json/wp/v2/posts");
  const data = await res.json();
  const pathList = data.map((path) => {
    return path.id.toString();
  });
  return {
    paths: [{ params: { post: pathList } }],
    fallback: true,
  };
}

export async function getStaticProps({ params }) {
  // Ber om ursäkt this looks like shit... but it works
  const slug = params.post[0];

  const pageRes = await fetch("http://localhost/wp-json/wp/v2/posts");
  const pageData = await pageRes.json();
  const page = pageData.find((page) => page.slug === slug);
  const res = await fetch(`http://localhost/wp-json/wp/v2/posts/${page?.id}`);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}
